global.lodash = require('lodash')
lodash.assign(global, require('./src/lib/constants'))
global.ai = require('./src/lib/ai')
global.D = require('./src/lib/detect')
global.ops = require('./src/lib/operations')
global.ttt = require('./src/ttt')